### ISSUE TITLE
toBeWithinRange

### ISSUE THREAD

**Issue by tinovyatkin** [JamieMason/expect-more#19]
Why `toBeWithinRange` is commented in Jest implementation and will it come back?

**Comment by JamieMason** [comment]
Sorry @tinovyatkin for the slow reply, I managed to unwatch some of my projects somehow and stopped getting notifications for them.

The TypeScript types for Jest don't support matchers with more than a certain number of arguments at the moment. I've not got around yet to submitting a PR. Once that is in we'll be able to use `toBeWithinRange` again.
