### ISSUE TITLE
expect(array).toBeArrayOfFunctions()

### ISSUE THREAD

**Issue by robross0606** [JamieMason/expect-more#44]
Assert collection is an Array containing functions.

**Comment by robross0606** [comment]
Is it possible to simulate this with `expect(array).toBeArrayOf(matcher)`?  If so, I couldn't figure out the syntax.

**Comment by JamieMason** [comment]
that's right @robross0606. The docs here in this public repo could do with some work but once installed [you will see this in intellisense](https://github.com/JamieMason/expect-more/blob/master/packages/expect-more-jest/src/to-be-array-of.ts#L12-L14) when hovering over `toBeArrayOf` in your IDE. 

So in your case you could get away with doing:

```ts
expect(myArray).toBeArrayOf(expect.toBeFunction());
```

**Comment by JamieMason** [comment]
I think this is complete
