### ISSUE TITLE
Similar functionality for jest expect standalone?

### ISSUE THREAD

**Issue by none100p** [JamieMason/expect-more#45]
There's a standalone package for [jest-expect](https://www.npmjs.com/package/expect), but it uses different namespace from jest itself, and also different type names for matchers, so it's impossible to simply reuse ```expect-more-jest``` package for this case.

It would really be very helpful to be able to extend that package with your matchers.

**Comment by JamieMason** [comment]
I'd be open to having this added but I don't use that standalone package, so it would need someone else to set it up initially.

**Comment by none100p** [comment]
Thanks for answer, I will probably give it a try soon.

**Comment by JamieMason** [comment]
Closing this one as stale for now.
