### ISSUE TITLE
Array expectations like toBeArrayIncludingOnly do not support asymmetric matching

### ISSUE THREAD

**Issue by robross0606** [JamieMason/expect-more#51]
## Description

When stating complex or partial matches on things like parameters, is is often necessary to compare the contents of objects in an array.  With standard expectations like `arrayContaining`, you can do this using asymmetric matchers like this:

```javascript
test('should contain important objects in array', () => {
    const array = [
        { 
            important: 'important',
            ignore: 'ignore'
        },
        {
            ignore: 'ignore',
        }
    ];

    expect(soy).toHaveBeenCalledWith(expect.arrayContaining(
        [expect.objectContaining({ important: 'important' })]
    ));
});
```

One would expect that expectations like `toBeArrayIncludingOnly` would follow the same semantic rules as `arrayContaining` and be a "drop in" replacement.  However, this is not currently true because `toBeArrayIncludingOnly` (and others) do not appear to support asymmetric matching.

## Suggested Solution

Array functions similar to `arrayContaining` should follow the same semantic rules and be "drop in" replacements by support asymmetric matchers.

**Comment by JamieMason** [comment]
Hey Rob, expect-more-jest doesn't currently understand asymmetric matchers when it receives one as an argument. This needs to happen, but until that is released we will need to only provide regular values as arguments to matchers from this library unfortunately.

**Comment by JamieMason** [comment]
This should now be possible in the following matchers from 5.5.0:

- toBeArrayIncludingAllOf
- toBeArrayIncludingOnly
- toBeArrayIncludingAnyOf
